version: 0.2

phases:
    build:
        command:
            - echo Entered the build phase...
            - mvn clean build package
    post_build:
        commands:
            - echo Build completed successfully
artifacts:
    files:
         - target/MedifyAPI-0.0.1-SNAPSHOT.jar
    discard-paths: yes
