version: 0.2

phases:
    build:
        command:
            - echo Entered the build phase...
            - mvn clean package
    post_build:
        commands:
            -echo Build completed successfully
artifacts:
    files:
        - target/medify-api.jar
    discard-paths: yes